---
- hosts: all
  remote_user: ec2-user
  become: yes
  become_user: root
  become_method: sudo
  tasks:
    - name: Download docker repos
      get_url:
        url: https://download.docker.com/linux/centos/docker-ce.repo
        dest: /etc/yum.repos.d/docker-ce.repo
        mode: 0440
    - name: Install EPEL repo.
      yum:
        name: https://dl.fedoraproject.org/pub/epel/epel-release-latest-{{ ansible_distribution_major_version }}.noarch.rpm
        state: present
    - name: Import EPEL GPG key.
      rpm_key:
        key: /etc/pki/rpm-gpg/RPM-GPG-KEY-EPEL-{{ ansible_distribution_major_version }}
        state: present
    - name: yum install things
      yum:
        name: yum-utils, lvm2, device-mapper-persistent-data, wget, container-selinux, pigz, docker-ce, python-pip
        enablerepo: "epel,rhui-REGION-rhel-server-extras"
        state: latest
    - name: pip install things
      pip:
        name: docker-py
    - name: start docker
      systemd:
        name: docker
        state: started
        enabled: yes
    - name: launch container
      docker_container:
        name: HW
        image: crccheck/hello-world
        ports: 80:8000
